# Generated by Django 3.2 on 2021-11-25 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireanswers',
            name='questionnaire_name_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.questionnairedata', verbose_name='Опрос'),
        ),
        migrations.AlterField(
            model_name='questionnaireanswers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='lection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lection_name', models.TextField(verbose_name='Название лекции')),
                ('lection_text', models.TextField(verbose_name='Текст лекции')),
                ('questionnaire_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.questionnairedata', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Лекция',
                'verbose_name_plural': 'Лекции',
            },
        ),
    ]
